- id: stylelint
  name: stylelint
  entry: stylelint
  language: node
  'types': ['css', 'scss', 'sass']
  args: []
  files: \.(css|scss|sass)$
  require_serial: false
  additional_dependencies: ["stylelint@13.13.1"]
  minimum_pre_commit_version: 0.7.0  # additional_dependencies
